environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TARGET: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-host %target% --default-toolchain none
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build: false

test_script:
- cargo test

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
