[package]
name = "deltachat-core-rust"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
edition = "2018"

[build-dependencies]
cc = "1.0.35"
pkg-config = "0.3"
bindgen = "0.49.0"

[dependencies]
c2rust-bitfields = "0.1.0"
libc = "0.2.51"
