[package]
name = "deltachat-core-rust"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
edition = "2018"

[lib]
name = "deltachat"
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
cc = "1.0.35"
pkg-config = "0.3"
cbindgen = "0.8.3"


[dependencies]
c2rust-bitfields = "0.1.0"
libc = "0.2.51"
pgp = "0.2.0"
failure = "0.1.5"
hex = "0.3.2"
sha2 = "0.8.0"
rand = "0.6.5"
smallvec = "0.6.9"
libsqlite3-sys = "0.14.0"
reqwest = "0.9.15"
