name: CI

on:
  pull_request:
  push:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    name: 3.7 python tests against core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@v1
        with:
           profile: minimal
           toolchain: nightly
           override: true
           components: rustfmt

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
          architecture: x64

      - run: bash ci_scripts/run-python.sh 
