name: CI

on:
  pull_request:
  push:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]

    steps:
    - uses: actions/checkout@master

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: check
      uses: actions-rs/cargo@v1
      if: matrix.rust == 'nightly'
      with:
        command:  check
        args: --all --bins --examples --tests

    - name: tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all

    - name: tests ignored
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all --release -- --ignored

  python_tests:
    name: 3.7 python tests against core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@v1
        with:
           profile: minimal
           toolchain: nightly
           override: true
           components: rustfmt
 
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
          architecture: x64

      - run: bash ci_scripts/run-python.sh 

  check_fmt:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

    - name: fmt
      run: cargo fmt --all -- --check

  clippy_check:
    name: Clippy check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy

    - name: clippy
      run: cargo clippy --all
